{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_cases_with_allure.py:18: AssertionError"}, "description": "this test fails", "start": 1602307590818, "stop": 1602307590819, "uuid": "eb53eec8-e8da-41e0-a695-b9313e685d05", "historyId": "2bd46fc80e35183ce53a4f1303b8db1c", "testCaseId": "8e5c6a8ffff1a26e29797cc89b410dc6", "fullName": "test_cases_with_allure#test_failure", "labels": [{"name": "suite", "value": "test_cases_with_allure"}, {"name": "host", "value": "mi-OptiPlex-7040"}, {"name": "thread", "value": "13502-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases_with_allure"}]}